---
- name: Ensure destination directory exists
  file:
    path: "{{ dest_dir }}"
    state: directory
    mode: '0755'
  ignore_errors: true

- name: Clone Git repository
  git:
    repo: "{{ repo_url }}"
    dest: "{{ dest_dir }}"
    version: main
    force: yes