---

- name: Create directory
  ansible.builtin.file:
    path: "{{ dest_dir }}"
    state: directory
    mode: '0755'
  become: true

# - name: Ensure destination directory exists
#   file:
#     path: "{{ dest_dir }}"
#     state: directory
#     mode: '0755'
  

- name: Clone Git repository
  git:
    repo: "{{ repo_url }}"
    dest: "{{ dest_dir }}"
    version: main
    force: yes
    accept_hostkey: yes
  environment:
    GIT_TERMINAL_PROMPT: "0"
    HOME: "/home/nts"

# - name: Delete directory
#   ansible.builtin.file:
#     path: "{{ dir_path }}"
#     state: absent